### ISSUE TITLE
Error: Internet Status Down!

### ISSUE THREAD

**Issue by diogo-gomes** [MSF-Jarvis/AIO-TWRP-Compiler#1]
I can't sync source code base repository of omni rom.

I have internet connection but when I run the script in Ubuntu 16.04, I get "Internet Status Down!"

Can you help me?

Thanks.

**Comment by MSF-Jarvis** [comment]
Hmm, that's a bit weird, honestly speaking though none of this code is mine, so I have no idea how it's working to detect that, but I'll look at it now.

**Comment by MSF-Jarvis** [comment]
Okay, just looked at it, it looks clean, no derps or anything to be seen so I have no idea what's wrong on your system. Closing this now.
