### ISSUE TITLE
Script Breaks with Characters in Model Name

### ISSUE THREAD

**Issue by chadrockey** [MSF-Jarvis/AIO-TWRP-Compiler#2]
@MSF-Jarvis do you have any tips for fixing the script to handle special characters in the model name?

I'm working on the ASUS Zenfone AR and it's model name is "msm-3.18"  This causes the build to break in many places.  I tried "msm318" but the script expects the original name because it looks at the boot.img and from the device.

**Comment by MSF-Jarvis** [comment]
No way your model name is msm-3.18 pal

**Comment by akhilnarang** [comment]
That *CANNOT* be your model name

**Comment by akhilnarang** [comment]
If that is, your OEM is worse than OnePlus leaving the name as generic in bootloader

**Comment by chadrockey** [comment]
@MSF-Jarvis do you know how to find the model name?  I downloaded the kernel source from Asus and it's in a directory called Asus/msm-3.18

http://dlcdnet.asus.com/pub/ASUS/ZenFone/ZS571KL/ASUS_A002-14.1600.1711.36-kernel-src.tar.zip

When I enter any other name, the script says that it expects device/Asus/msm-3.18/kernel that it reads from the boot.img

---------------
Separately, I confirmed that the reason it wasn't working was because of the lunch command.  I hand tweaked the scripts to just called it omni_msm318-eng and I get an output recovery.img file.  Unfortunately, I can't get that recovery file to boot, it hangs, so I need to find documentation for how to debug the output recovery.img files.

Here's my device repo: https://github.com/chadrockey/msm-3.18_twrp

**Comment by chadrockey** [comment]
For example, when I specify the model as "ASUS_A002" as reported DeviceName.DeviceInfo.model, I get this error:
make: *** No rule to make target 'device/Asus/msm-3.18/kernel', needed by '/home/chadrockey/omni/out/target/product/ASUS_A002/kernel'.  Stop.

**Comment by MSF-Jarvis** [comment]
You don't really have a clue about what you're doing so I'd suggest you go through some guides over at XDA before attempting to use this tool.

**Comment by chadrockey** [comment]
So the proper response is: "Hmm, try to find or check the build.prop to look for ro.product.device, that will show you the codename you'll want to use and let us know if that still has characters that break the script.  Good luck!"

In this case it's ASUS_A002, but I ultimately had to use a different method than this script.
